using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StardewArchipelago.Constants
{
    public static class AnimalNames
    {
        public static readonly string[] AllNames = new[]
        {
            "Swan",
            "Cheetah",
            "Chimpanzee",
            "Alpaca",
            "Kangaroo",
            "Cockroach",
            "Spoonbill",
            "Stingray",
            "Bee",
            "Gorilla",
            "Wolf",
            "Opossum",
            "Dove",
            "Whale",
            "Wombat",
            "Quail",
            "Pheasant",
            "Raptor",
            "Crab",
            "Peafowl",
            "Dolphin",
            "Lyrebird",
            "Moth",
            "Heron",
            "Wasp",
            "Salmon",
            "Goshawk",
            "Sandpiper",
            "Rhinoceros",
            "Fox",
            "Antelope",
            "Gnu",
            "Penguin",
            "Viper",
            "Emu",
            "Alligator",
            "Newt",
            "Shark",
            "Skunk",
            "Goose",
            "Otter",
            "Salamander",
            "Fly",
            "Ladybug",
            "Lizard",
            "Gnat",
            "Owl",
            "Deer",
            "Lark",
            "Human",
            "Tyrannosaurus",
            "Starfish",
            "Bobcat",
            "Nightingale",
            "Narwhal",
            "Peccary",
            "Armadillo",
            "Hedgehog",
            "Badger",
            "Raven",
            "Grasshopper",
            "Pelican",
            "Gerbil",
            "Panther",
            "Termite",
            "Dunlin",
            "Jellyfish",
            "Butterfly",
            "Eel",
            "Echidna",
            "Crocodile",
            "Crow",
            "Toucan",
            "Tiger",
            "Rook",
            "Jay",
            "Giraffe",
            "Starling",
            "Turtle",
            "Partridge",
            "Weasel",
            "Porcupine",
            "Camel",
            "Beetle",
            "Pug",
            "Lobster",
            "Snail",
            "Frog",
            "Jaguar",
            "Herring",
            "Finch",
            "Wildebeest",
            "Gecko",
            "Ape",
            "Oyster",
            "Baboon",
            "Ferret",
            "Squirrel",
            "Hornet",
            "Axolotl",
            "Chinchilla",
            "Cormorant",
            "Hyena",
            "Chough",
            "Meerkat",
            "Falcon",
            "Cardinal",
            "Flamingo",
            "Raccoon",
            "Kingbird",
            "Elephant",
            "Platypus",
            "Albatross",
            "Binturong",
            "Cod",
            "Hippopotamus",
            "Hare",
            "Sardine",
            "Grouse",
            "Eagle",
            "Mongoose",
            "Hawk",
            "Toad",
            "Monkey",
            "Koala",
            "Duck",
            "Zebra",
            "Wallaby",
            "Kinkajou",
            "Mouse",
            "Guanaco",
            "Goldfinch",
            "Lapwing",
            "Beaver",
            "Lion",
            "Thrush",
            "Mosquito",
            "Llama",
            "Cobra",
            "Crane",
            "Ant",
            "Leopard",
            "Dragon",
            "Bat",
            "Seal",
            "Hamster",
        };
        // To add later
        // Shrike
        // Capybara
        // Pterodactyl
        // Brontosaurus
        // Triceratops
        // Human
    }

}
