// ReSharper disable StringLiteralTypo
namespace StardewArchipelago.Constants
{
    public class Community
    {
        public static readonly string[] AllNames =
        {
            "Albrekka",
            "Alchav",
            "Angela",
            "angelrosewood",
            "Angkelic",
            "ArgonMatrix",
            "axe_y",
            "beauxq",
            "Berserker",
            "Black Sliver",
            "blastron",
            "BootsinSoots",
            "BruceWinless",
            "CaitSith2",
            "Captain Canadia",
            "Celeste",
            "ChiniganDoodles",
            "Damocles",
            "dewin",
            "el_",
            "emmalution",
            "Espeon",
            "eudaimonistic",
            "Exempt-Medic",
            "Farrak Kilhn",
            "Figment",
            "Fly Sniper",
            "Frazzleduck",
            "Heinermann",
            "Iritav100",
            "Ishigh",
            "JaredWeakStrike",
            "Jarno",
            "jat2980",
            "jennnifer",
            "Jouramie",
            "Justice",
            "Kaito Kid",
            "Kankuro",
            "KelioMZX",
            "Kimou00",
            "KittyAshy",
            "Kono Tyran",
            "Lady Redacted",
            "LeftoverLyzard",
            "Liarose",
            "lordlou",
            "Madolinn",
            "MaeDawn",
            "Magnemania",
            "Marech",
            "Margot",
            "Mati",
            "Mav",
            "MeleneV",
            "mewlif",
            "Mistik",
            "myserval",
            "N00byKing",
            "Nada",
            // "NinoKito",
            "Noca",
            "ParkenHarbor",
            "Phar",
            "PoryGone",
            "PreludeWish",
            "ProfBytes",
            "RaspberrySpaceJam",
            "Relissa",
            "Rosalie",
            "SakuraTsubasa",
            "Salmence",
            "Salzkorn",
            "TheSamanthaTM",
            "Scipio",
            "SlyRyD",
            "Smorgasbord",
            "Sneaki",
            "Snow",
            "Squimble",
            "Sraw",
            "SunnyBat",
            "TerraGuild",
            "TheCondor",
            "TheHaboo",
            "TheRedWolfe",
            "Thestral Things",
            "toaster",
            "Trev",
            "Violet",
            "WhySoThirstyy",
            "Yellow_Meep",
            "zig",
            "Ziktofel",
        };
    }
}
